### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mhamidjamil**
ThingSpeak values are not updating i think it is because my university account is suspended. I'll check and update in PR comments.

### CODE REVIEW

**Comment by mhamidjamil** [comment]
Value is updateable from postman so there might be a code issue, @wasey-rao you can create an issue if you face same issue with your module.

**Review by wasey-rao — CHANGES_REQUESTED** [review]
seems fine but what about #85 and #79 last feature ? are they done? and  #82 is the important one I'll merge PR when i got the PR with signature that this issue got fixed.

**Comment by wasey-rao** [comment]
this PR code's neither stable nor working, make it stable in 24 hours otherwise it will be closed.
@mhamidjamil @hamidjamil0420

**Comment by mhamidjamil** [comment]
code it working fine till **`version 5.3.5`** i have verified it now. Can you please share which errors or blockers you are facing and please also mention the file name and version tag if possible. @wasey-rao

**Comment by mhamidjamil** [comment]
@wasey-rao can you please now verify the code and also the issue as it is fixed on my side now, if this PR is merged then I'll Start working on #82, But in this PR debugging pattern is added which will help me to sort out the issue.

**Pull request merged**
